    <optgroup label="A">

<option value="Côte d'Ivoire">Côte d'Ivoire</option>
<option value="Afghanistan">Afghanistan</option>
        <option value="Afghanistan">Afrique du Sud</option>
        <option value="Albanie">Albanie</option>
        <option value="Algérie">Algérie</option>
        <option value="Allemagne">Allemagne</option>
        <option value="Andorre">Andorre</option>
        <option value="Angola">Angola</option>
        <option value="Anguilla">Anguilla</option>
        <option value="Antarctique">Antarctique</option>
        <option value="Antigua-et-Barbuda">Antigua-et-Barbuda</option>
        <option value="Antilles néerlandaises">Antilles néerlandaises</option>
        <option value="Arabie saoudite">Arabie saoudite</option>
        <option value="Argentine">Argentine</option>
        <option value="Arménie">Arménie</option>
        <option value="Aruba">Aruba</option>
        <option value="Australie">Australie</option>
        <option value="Autriche">Autriche</option>
        <option value="Azerbaïdjan">Azerbaïdjan</option>
    </optgroup>
    <optgroup label="B">
<option value="Bahamas">Bahamas</option>
        <option value="Bahreïn">Bahreïn</option>
        <option value="Bangladesh">Bangladesh</option>
        <option value="Barbade">Barbade</option>
        <option value="Belgique">Belgique</option>
        <option value="Belize">Belize</option>
        <option value="Bénin">Bénin</option>
        <option value="Bermudes">Bermudes</option>
        <option value="Bhoutan">Bhoutan</option>
        <option value="Biélorussie">Biélorussie</option>
        <option value="Bolivie">Bolivie</option>
        <option value="Bosnie-et-Herzégovine">Bosnie-et-Herzégovine</option>
        <option value="Botswana">Botswana</option>
        <option value="Brésil">Brésil</option>
        <option value="Brunei Darussalam">Brunei Darussalam</option>
        <option value="Bulgarie">Bulgarie</option>
        <option value="Burkina Faso">Burkina Faso</option>
        <option value="Burundi">Burundi</option>
    </optgroup>
    <optgroup label="C">
<option value="Cambodge">Cambodge</option>
        <option value="Cameroun">Cameroun</option>
        <option value="Canada">Canada</option>
        <option value="Cap-Vert">Cap-Vert</option>
        <option value="Chili">Chili</option>
        <option value="Chine">Chine</option>
        <option value="Chypre">Chypre</option>
        <option value="Colombie">Colombie</option>
        <option value="Comores">Comores</option>
        <option value="Congo">Congo</option>
        <option value="Costa Rica">Costa Rica</option>
        <option value="Côte d'Ivoire">Côte d'Ivoire</option>
        <option value="Croatie">Croatie</option>
        <option value="Cuba">Cuba</option>
    </optgroup>
    <optgroup label="D">
<option value="Danemark">Danemark</option>
        <option value="Djibouti">Djibouti</option>
        <option value="Dominique">Dominique</option>
    </optgroup>
    <optgroup label="E">
<option value="Égypte">Égypte</option>
        <option value="El Salvador">El Salvador</option>
        <option value="Émirats arabes unis">Émirats arabes unis</option>
        <option value="Équateur">Équateur</option>
        <option value="Érythrée">Érythrée</option>
        <option value="Espagne">Espagne</option>
        <option value="Estonie">Estonie</option>
        <option value="États fédérés de Micronésie">États fédérés de Micronésie</option>
        <option value="États-Unis">États-Unis</option>
        <option value="Éthiopie">Éthiopie</option>
    </optgroup>
    <optgroup label="F">
<option value="Fidji">Fidji</option>
        <option value="Finlande">Finlande</option>
        <option value="France">France</option>
    </optgroup>
    <optgroup label="G">
<option value="Gabon">Gabon</option>
        <option value="Gambie">Gambie</option>
        <option value="Gambie">Géorgie</option>
        <option value="Ghana">Ghana</option>
        <option value="Gibraltar">Gibraltar</option>
        <option value="Grèce">Grèce</option>
        <option value="Grenade">Grenade</option>
        <option value="Groenland">Groenland</option>
        <option value="Guadeloupe">Guadeloupe</option>
        <option value="Guam">Guam</option>
        <option value="Guatemala">Guatemala</option>
        <option value="Guinée">Guinée</option>
        <option value="Guinée équatoriale">Guinée équatoriale</option>
        <option value="Guinée-Bissau">Guinée-Bissau</option>
        <option value="Guyane">Guyane</option>
    </optgroup>
    <optgroup label="H">
<option value="Haïti">Haïti</option>
        <option value="Honduras">Honduras</option>
        <option value="Hong Kong">Hong Kong</option>
        <option value="Hongrie">Hongrie</option>
    </optgroup>
    <optgroup label="I">
<option value="Ile Bouvet">Ile Bouvet</option>
        <option value="Ile Christmas">Ile Christmas</option>
        <option value="Île Norfolk">Île Norfolk</option>
        <option value="Île Pitcairn">Île Pitcairn</option>
        <option value="Iles Aland">Iles Aland</option>
        <option value="Iles Cayman">Iles Cayman</option>
        <option value="Iles Cook">Iles Cook</option>
        <option value="Îles Féroé">Îles Féroé</option>
        <option value="Îles Heard-et-MacDonald">Îles Heard-et-MacDonald</option>
        <option value="Îles Malouines">Îles Malouines</option>
        <option value="Îles Mariannes du Nord">Îles Mariannes du Nord</option>
        <option value="Îles Marshall">Îles Marshall</option>
        <option value="Îles mineures éloignées des États-Unis">Îles mineures éloignées des États-Unis</option>
        <option value="Îles Salomon">Îles Salomon</option>
        <option value="Îles Turques-et-Caïques">Îles Turques-et-Caïques</option>
        <option value="Îles Vierges britanniques">Îles Vierges britanniques</option>
        <option value="Îles Vierges des États-Unis">Îles Vierges des États-Unis</option>
        <option value="Inde">Inde</option>
        <option value="Indonésie">Indonésie</option>
        <option value="Iraq">Iraq</option>
        <option value="Irlande">Irlande</option>
        <option value="Islande">Islande</option>
        <option value="Israël">Israël</option>
        <option value="Italie">Italie</option>
    </optgroup>
    <optgroup label="J">
<option value="Jamahiriya arabe libyenne">Jamahiriya arabe libyenne</option>
        <option value="Jamaïque">Jamaïque</option>
        <option value="Japon">Japon</option>
        <option value="Jordanie">Jordanie</option>
    </optgroup>
    <optgroup label="K">
<option value="Kazakhstan">Kazakhstan</option>
        <option value="Kenya">Kenya</option>
        <option value="Kirghizistan">Kirghizistan</option>
        <option value="Kiribati">Kiribati</option>
        <option value="Koweït">Koweït</option>
    </optgroup>
    <optgroup label="L">
<option value="Lesotho">Lesotho</option>
        <option value="Lettonie">Lettonie</option>
        <option value="Liban">Liban</option>
        <option value="Libéria">Libéria</option>
        <option value="Liechtenstein">Liechtenstein</option>
        <option value="Lituanie">Lituanie</option>
        <option value="Luxembourg">Luxembourg</option>
    </optgroup>
    <optgroup label="M">
<option value="Macao">Macao</option>
        <option value="Madagascar">Madagascar</option>
        <option value="Malaisie">Malaisie</option>
        <option value="Malawi">Malawi</option>
        <option value="Maldives">Maldives</option>
        <option value="Mali">Mali</option>
        <option value="Malte">Malte</option>
        <option value="Maroc">Maroc</option>
        <option value="Martinique">Martinique</option>
        <option value="Maurice">Maurice</option>
        <option value="Mauritanie">Mauritanie</option>
        <option value="Mayotte">Mayotte</option>
        <option value="Mexique">Mexique</option>
        <option value="Monaco">Monaco</option>
        <option value="Mongolie">Mongolie</option>
        <option value="Montserrat">Montserrat</option>
        <option value="Mozambique">Mozambique</option>
        <option value="Myanmar">Myanmar</option>
    </optgroup>
    <optgroup label="N">
<option value="Namibie">Namibie</option>
        <option value="Nauru">Nauru</option>
        <option value="Népal">Népal</option>
        <option value="Nicaragua">Nicaragua</option>
        <option value="Niger">Niger</option>
        <option value="Nigéria">Nigéria</option>
        <option value="Niué">Niué</option>
        <option value="Norvège">Norvège</option>
        <option value="Nouvelle-Calédonie">Nouvelle-Calédonie</option>
        <option value="Nouvelle-Zélande">Nouvelle-Zélande</option>
    </optgroup>
    <optgroup label="O">
<option value="Oman">Oman</option>
        <option value="Ouganda">Ouganda</option>
        <option value="Ouzbékistan">Ouzbékistan</option>
    </optgroup>
    <optgroup label="P">
<option value="Pakistan">Pakistan</option>
        <option value="Palaos">Palaos</option>
        <option value="Panama">Panama</option>
        <option value="Papouasie-Nouvelle-Guinée">Papouasie-Nouvelle-Guinée</option>
        <option value="Paraguay">Paraguay</option>
        <option value="Pays-Bas">Pays-Bas</option>
        <option value="Pérou">Pérou</option>
        <option value="Philippines">Philippines</option>
        <option value="Pologne">Pologne</option>
        <option value="Polynésie française">Polynésie française</option>
        <option value="Porto Rico">Porto Rico</option>
        <option value="Portugal">Portugal</option>
        <option value="Province chinoise de Taiwan">Province chinoise de Taiwan</option>
    </optgroup>
    <optgroup label="Q">
<option value="Qatar">Qatar</option>
    </optgroup>
    <optgroup label="R">
<option value="République arabe syrienne">République arabe syrienne</option>
        <option value="République centrafricaine">République centrafricaine</option>
        <option value="République de Corée">République de Corée</option>
        <option value="République de Moldavie">République de Moldavie</option>
        <option value="République démocratique du Congo">République démocratique du Congo</option>
        <option value="République dominicaine">République dominicaine</option>
        <option value="République islamique d'Iran">République islamique d'Iran</option>
        <option value="République populaire démocratique de Corée">République populaire démocratique de Corée</option>
        <option value="République Populaire du Laos">République Populaire du Laos</option>
        <option value="République tchèque">République tchèque</option>
        <option value="République-Unie de Tanzanie">République-Unie de Tanzanie</option>
        <option value="Réunion">Réunion</option>
        <option value="Roumanie">Roumanie</option>
        <option value="Royaume-Uni">Royaume-Uni</option>
        <option value="Russie">Russie</option>
        <option value="Rwanda">Rwanda</option>
    </optgroup>
    <optgroup label="S">
<option value="Sahara occidental">Sahara occidental</option>
        <option value="Saint-Christophe-et-Niévès">Saint-Christophe-et-Niévès</option>
        <option value="Saint-Marin">Saint-Marin</option>
        <option value="Saint-Pierre-et-Miquelon">Saint-Pierre-et-Miquelon</option>
        <option value="Saint-Siège (Cité du Vatican)">Saint-Siège (Cité du Vatican)</option>
        <option value="Saint-Vincent-et-les Grenadines">Saint-Vincent-et-les Grenadines</option>
        <option value="Sainte-Hélène">Sainte-Hélène</option>
        <option value="Sainte-Lucie">Sainte-Lucie</option>
        <option value="Samoa">Samoa</option>
        <option value="Samoa américaines">Samoa américaines</option>
        <option value="Sao Tomé-et-Principe">Sao Tomé-et-Principe</option>
        <option value="Sénégal">Sénégal</option>
        <option value="Serbie-et-Monténégro">Serbie-et-Monténégro</option>
        <option value="Seychelles">Seychelles</option>
        <option value="Sierra Leone">Sierra Leone</option>
        <option value="Singapour">Singapour</option>
        <option value="Slovaquie">Slovaquie</option>
        <option value="Slovénie">Slovénie</option>
        <option value="Somalie">Somalie</option>
        <option value="Soudan">Soudan</option>
        <option value="Sri Lanka">Sri Lanka</option>
        <option value="Suède">Suède</option>
        <option value="Suisse">Suisse</option>
        <option value="Suriname">Suriname</option>
        <option value="Svalbard et Jan Mayen">Svalbard et Jan Mayen</option>
        <option value="Swaziland">Swaziland</option>
    </optgroup>
    <optgroup label="T">
<option value="Tadjikistan">Tadjikistan</option>
        <option value="Tchad">Tchad</option>
        <option value="Thaïlande">Thaïlande</option>
        <option value="Togo">Togo</option>
        <option value="Tokelau">Tokelau</option>
        <option value="Tonga">Tonga</option>
        <option value="Trinité-et-Tobago">Trinité-et-Tobago</option>
        <option value="Tunisie">Tunisie</option>
        <option value="Turkménistan">Turkménistan</option>
        <option value="Turquie">Turquie</option>
        <option value="Tuvalu">Tuvalu</option>
    </optgroup>
    <optgroup label="U">
<option value="Ukraine">Ukraine</option>
        <option value="Uruguay">Uruguay</option>
    </optgroup>
    <optgroup label="V">
<option value="Vanuatu">Vanuatu</option>
        <option value="Vénézuéla">Vénézuéla</option>
        <option value="Vietnam">Vietnam</option>
    </optgroup>
    <optgroup label="W">
<option value="Wallis-et-Futuna">Wallis-et-Futuna</option>
    </optgroup>
    <optgroup label="Y">
<option value="Yémen">Yémen</option>
    </optgroup>
    <optgroup label="Z">
<option value="Zambie">Zambie</option>
        <option value="Zimbabwe">Zimbabwe</option>
    </optgroup>